"""initial db setup

Revision ID: 1b6e40c7ff3b
Revises: 
Create Date: 2025-11-11 20:45:32.914455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b6e40c7ff3b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questionsandanswers', 'query',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('questionsandanswers', 'answer',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('questionsandanswers', 'answer',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('questionsandanswers', 'query',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
