"""added indexes in chats and questions_answers

Revision ID: 23774f0de7a7
Revises: 4abb73133b00
Create Date: 2025-11-11 21:20:30.867899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23774f0de7a7'
down_revision: Union[str, Sequence[str], None] = '4abb73133b00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_chat_id', 'chats', ['uuid'], unique=False)
    op.create_index('idx_user_uid', 'chats', ['user_uid'], unique=False)
    op.create_index('idx_chat_uid', 'questionsandanswers', ['chat_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chat_uid', table_name='questionsandanswers')
    op.drop_index('idx_user_uid', table_name='chats')
    op.drop_index('idx_chat_id', table_name='chats')
    # ### end Alembic commands ###
