"""Fixed created_at column to not put null value in db

Revision ID: a2115fafd823
Revises: a2d7a8bd9d16
Create Date: 2025-12-24 20:08:50.602998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2115fafd823'
down_revision: Union[str, Sequence[str], None] = 'a2d7a8bd9d16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
