"""Changed datatype to text

Revision ID: a2d7a8bd9d16
Revises: 23774f0de7a7
Create Date: 2025-11-13 22:02:38.143835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2d7a8bd9d16'
down_revision: Union[str, Sequence[str], None] = '23774f0de7a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questionsandanswers', 'query',
               existing_type=sa.VARCHAR(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('questionsandanswers', 'answer',
               existing_type=sa.VARCHAR(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questionsandanswers', 'answer',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('questionsandanswers', 'query',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
