"""some changes

Revision ID: 5720f047e082
Revises: a82a0210dc37
Create Date: 2026-06-21 10:35:06.742138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5720f047e082'
down_revision: Union[str, Sequence[str], None] = 'a82a0210dc37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('yt_video_id', sa.TEXT(), nullable=False),
    sa.Column('video_title', sa.TEXT(), nullable=True),
    sa.Column('duration_seconds', sa.NUMERIC(), nullable=True),
    sa.Column('processing_status', postgresql.ENUM('STARTED', 'PENDING', 'COMPLETED', 'FAILED', name='yt_video_processing_status_enum'), nullable=False),
    sa.Column('transcript_text', sa.TEXT(), nullable=True),
    sa.Column('video_description', sa.TEXT(), nullable=True),
    sa.Column('lang_code', sa.TEXT(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('yt_video_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('role', postgresql.ENUM('SYSTEM', 'USER', 'ASSISTANT', name='messages_role_enum'), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('tokens', sa.NUMERIC(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('messagses_idx_chat_id_created_at', 'messages', ['chat_id', sa.literal_column('created_at DESC')], unique=False)
    op.add_column('chats', sa.Column('yt_video_id', sa.TEXT(), nullable=False))
    op.drop_table('conversations')
    op.drop_constraint(op.f('chats_linked_video_id_fkey'), 'chats', type_='foreignkey')
    op.drop_index(op.f('ix_chats_linked_video_id'), table_name='chats')
    op.drop_table('video_info')
    op.create_index('chats_idx_chat_id_created_at', 'chats', ['id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('chats_idx_youtube_video_id', 'chats', ['yt_video_id'], unique=False)
    op.create_foreign_key(None, 'chats', 'videos', ['yt_video_id'], ['yt_video_id'], ondelete='RESTRICT')
    op.drop_column('chats', 'linked_video_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('linked_video_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.create_foreign_key(op.f('chats_linked_video_id_fkey'), 'chats', 'video_info', ['linked_video_id'], ['video_id'], ondelete='SET NULL')
    op.drop_index('chats_idx_youtube_video_id', table_name='chats')
    op.drop_index('chats_idx_chat_id_created_at', table_name='chats')
    op.create_index(op.f('ix_chats_linked_video_id'), 'chats', ['linked_video_id'], unique=False)
    op.drop_column('chats', 'yt_video_id')
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_query', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('assistant_reply', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name=op.f('conversations_chat_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'chat_id', name=op.f('conversations_pkey'))
    )
    op.create_table('video_info',
    sa.Column('video_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('video_loaded', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_in_vdb', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('transcript_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('video_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lang_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('video_id', name=op.f('video_info_pkey'))
    )
    op.drop_index('messagses_idx_chat_id_created_at', table_name='messages')
    op.drop_table('messages')
    op.drop_table('videos')
    # ### end Alembic commands ###
