"""new enum structure

Revision ID: 712c0ac25c6e
Revises: 5720f047e082
Create Date: 2026-06-21 13:32:20.660662

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "712c0ac25c6e"
down_revision: Union[str, Sequence[str], None] = "5720f047e082"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE processing_status ADD VALUE 'UNPROCESSABLE';")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
