"""initial

Revision ID: a82a0210dc37
Revises: 
Create Date: 2026-06-18 14:10:27.191955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a82a0210dc37'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('video_info',
    sa.Column('video_id', sa.TEXT(), nullable=False),
    sa.Column('video_loaded', sa.BOOLEAN(), nullable=False),
    sa.Column('is_in_vdb', sa.BOOLEAN(), nullable=False),
    sa.Column('transcript_text', sa.TEXT(), nullable=True),
    sa.Column('video_description', sa.TEXT(), nullable=True),
    sa.Column('lang_code', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('video_id')
    )
    op.create_table('chats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('linked_video_id', sa.TEXT(), nullable=True),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['linked_video_id'], ['video_info.video_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_linked_video_id'), 'chats', ['linked_video_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('user_query', sa.TEXT(), nullable=False),
    sa.Column('assistant_reply', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'chat_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversations')
    op.drop_index(op.f('ix_chats_linked_video_id'), table_name='chats')
    op.drop_table('chats')
    op.drop_table('video_info')
    op.drop_table('users')
    # ### end Alembic commands ###
